ETF_UNIVERSE = [
    "SPY","QQQ","IWM","DIA","XLK","XLF","XLE","XLI","XLV","XLY","XLP","XLU","XLB","XLRE","XLC",
    "VTI","VOO","IVV","RSP","VUG","VTV","VB","VO","VV","IWF","IWD","IJR","IJH","MDY",
    "SMH","SOXX","IGV","XBI","IBB","IHI","KRE","KBE","XRT","ITA","IYT","XHB",
    "VNQ","IYR","TLT","IEF","SHY","LQD","HYG","GLD","SLV","DBC"
]
PAIR_CORRELATION_MIN=0.82
ROLLING_WINDOW=60
INITIAL_CAPITAL=100_000.0
POSITION_FRACTION=0.10
WALK_FORWARD_WINDOWS=5
MIN_TEST_TRADES=8
BASE_COST_BPS=8.0
COST_STRESS_BPS=[8.0,15.0,25.0]
PARAMETER_GRID=[(1.75,0.50),(2.00,0.50),(2.25,0.50),(2.00,0.25),(2.00,0.75)]
HOLDOUT_FRACTION=0.15

# Frozen forward-paper experiment. Do not tune these rules using future results.
FORWARD_START_DATE="2026-09-29"
FORWARD_STRATEGIES=[("IWF","SPY"),("IWD","MDY"),("IJH","IWM")]
FORWARD_ENTRY_Z=2.0
FORWARD_EXIT_Z=0.5
FORWARD_COST_BPS=8.0
