ETF_UNIVERSE = [
    "SPY","QQQ","IWM","DIA",
    "XLK","XLF","XLE","XLI","XLV","XLY","XLP","XLU"
]

LOOKBACK_DAYS = 756
PAIR_CORRELATION_MIN = 0.80
Z_ENTRY = 2.0
Z_EXIT = 0.5
ROLLING_WINDOW = 60
INITIAL_CAPITAL = 100_000.0
POSITION_FRACTION = 0.10
ROUND_TRIP_COST_BPS = 8.0
