ETF_UNIVERSE = [
    "SPY","QQQ","IWM","DIA",
    "XLK","XLF","XLE","XLI","XLV","XLY","XLP","XLU","XLB","XLRE","XLC",
    "VTI","VOO","IVV","RSP","VUG","VTV","VB","VO","VV",
    "IWF","IWD","IJR","IJH","MDY",
    "SMH","SOXX","IGV","XBI","IBB","IHI",
    "KRE","KBE","XRT","ITA","IYT","XHB",
    "VNQ","IYR","TLT","IEF","SHY","LQD","HYG",
    "GLD","SLV","DBC"
]
PAIR_CORRELATION_MIN = 0.82
Z_ENTRY = 2.0
Z_EXIT = 0.5
ROLLING_WINDOW = 60
INITIAL_CAPITAL = 100_000.0
POSITION_FRACTION = 0.10
ROUND_TRIP_COST_BPS = 8.0
WALK_FORWARD_WINDOWS = 5
MIN_TEST_TRADES = 6
